######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 27 16:45:28 2011
######################################################################

CONFIG += debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += edge.h graph.h graph_view.h main_window.h misc.h vertex.h
SOURCES += edge.cpp graph.cpp graph_view.cpp main.cpp main_window.cpp vertex.cpp
RESOURCES += graphbag.qrc
